backend:
  name: git-gateway

media_folder: static/media
public_folder: static/media
publish_mode: editorial_workflow
display_url: https://betterdocs.us

collections:
  - name: "themes" # Used in routes, e.g., /admin/collections/blog
    label: "Themes" # Used in the UI
    folder: "src/themes/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    delete: false
    media_folder: "images/themes"
    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "title"
        widget: "string"
        default: "{Theme Name}"

      - label: "Author"
        name: "author" 
        widget: "string"
        default: "{Author}"

      - label: "Description"
        name: "description"
        widget: "markdown"

      - label: "Download URL"
        name: "download"
        widget: "string"

      - label: "Github" 
        name: "github"
        widget: "string"
        default: "https://github.com/{Author}/"

      - label: "Support URL"
        name: "support"
        widget: "string"
        default: "https://discord.gg/invite"

      - label: "Demo URL"
        name: "demo"
        widget: "string"
        default: "https://rawcdn.githack.com/USER/REPO/master/"

      - label: "Tags (Seperated by comma ',')" 
        name: "tags"
        widget: "list"
        required: false

      - label: "Supported Software (Seperated by comma ',')" 
        name: "software"
        widget: "list"
        required: false

      - label: "Images"
        name: "images"
        widget: "list"
        required: false
        fields:
          - label: "Image Name"
            name: "name"
            default: " {NAME} Preview "
            widget: "string"
          - label: "Image"
            name: "image"
            widget: "image"
        
      - label: "Status of your theme"
        name: "status"
        widget: "select"
        options: ["Updated","Outdated"]

      - label: "Auto Download?"
        name: "auto"
        widget: "boolean"

      - label: "Style" 
        name: "style"
        widget: "select"
        options: ["dark", "light"]
        default: "dark"

      - label: "Github Comment ID" 
        name: "ghcommentid"
        widget: "number"
        required: false

      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "product"

      - label: "Publish Date"
        name: "date" 
        widget: "datetime"

  - name: "plugins" # Used in routes, e.g., /admin/collections/blog
    label: "Plugins" # Used in the UI
    folder: "src/plugins/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    media_folder: "images/plugins"
    delete: false
    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "title"
        widget: "string"
        default: "{Plugin Name}"

      - label: "Author"
        name: "author" 
        widget: "string"
        default: "{Author}"

      - label: "Description"
        name: "description"
        widget: "markdown"

      - label: "Download URL"
        name: "download"
        widget: "string"

      - label: "Github" 
        name: "github"
        widget: "string"
        default: "https://github.com/{Author}/"

      - label: "Support URL"
        name: "support"
        widget: "string"
        default: "https://discord.gg/invite"

      - label: "Tags (Seperated by comma ',')" 
        name: "tags"
        widget: "list"
        required: false
        
      - label: "Supported Software (Seperated by comma ',')" 
        name: "software"
        widget: "list"

      - label: "Images"
        name: "images"
        required: false
        widget: "list"
        fields:
          - label: "Image Name"
            name: "name"
            widget: "string"
          - label: "Image"
            name: "image"
            widget: "image"

      - label: "Status of your plugin"
        name: "status"
        widget: "select"
        options: ["Updated","Outdated"]

      - label: "Auto Download?"
        name: "auto"
        widget: "boolean"

      - label: "Github Comment ID" 
        name: "ghcommentid"
        widget: "number"
        required: false

      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "product"

      - label: "Publish Date"
        name: "date" 
        widget: "datetime"